### ISSUE TITLE
Problem  config file with authentification

### ISSUE THREAD

**Issue by IvanAbakumov** [singun-lxd/OpenVpnClient#3]
Hi!
I decided to see how this application works.
And since it works fine, if the configuration file does not contain this parameter  "auth-user-pass".
But the VPN-server to which I connect, contains a username and password. And because of this, I can not connect to it.

Please, help me.

**Comment by shahwaiz90** [comment]
Yeah, same problem with me. May be needs some attribute we can set from the config file? Any solutions?

**Comment by IvanAbakumov** [comment]
@shahwaiz90 I found a solution.

**Comment by IvanAbakumov** [comment]
@shahwaiz90 
Variables "mPassword" and "mUsername" in the class "VpnProfile" do not work.
Instead, you must open the class "OpenVpnConnector". It has a static method "startVpnInternal".
And it has variables "vp.mUsername" and "vp.mPassword" in which you must pass the login and password. To prank it, just write your data in this method and connect the same configuration file.

Try and email me if you succeed. Maybe I could forget some details.

**Comment by shahwaiz90** [comment]
Yeah me too, startVpnInternal in this function there is a username and password field. Thanks man for your quick response though!

**Comment by shahwaiz90** [comment]
You should close the issue though.
